### ISSUE TITLE
MAYGEN fails to generate graphs for input MF with less than 3 heavy atoms

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/MAYGEN#12]

**Comment by steinbeck** [comment]
java -jar MAYGEN.jar -f C2H6
MAYGEN is generating isomers of C2H6...
The number of structures is: 0
Time: .023 seconds

**Comment by MehmetAzizYirik** [comment]
@steinbeck The problem is solved and graphs for input MF with less than 3 heavy atoms can be generated in the new version.
