### ISSUE TITLE
Add links in readme ?

### ISSUE THREAD

**Issue by lpatiny** [MehmetAzizYirik/MAYGEN#124]
Thanks for this excellent code !

Just to let you know:

I created a webservice for your code:

https://maygen.cheminfo.org/documentation/static/index.html

I did a graphical interface so that my students can easily use it

https://www.cheminfo.org/?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F7cead2ae3da71090cb17baa3856ea38b%2Fview.json

Maybe you would like to add those links in the README

**Comment by MehmetAzizYirik** [comment]
> Thanks for this excellent code !
> 
> Just to let you know:
> 
> I created a webservice for your code:
> 
> https://maygen.cheminfo.org/documentation/static/index.html
> 
> I did a graphical interface so that my students can easily use it
> 
> https://www.cheminfo.org/?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F7cead2ae3da71090cb17baa3856ea38b%2Fview.json
> 
> Maybe you would like to add those links in the README

Thanks Luc for your  nice feedback and nice to hear about this webservice. For sure, I am going to add the links in the README.

**Comment by MehmetAzizYirik** [comment]
@lpatiny 

A subsection is created in the README for the webservice and both links are added. Thanks Luc.
