### ISSUE TITLE
Add test for uneven degree sum to recognise early that no structure will be generated

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/MAYGEN#14]
java -jar MAYGEN.jar -f C5N2O5H1 -o /dev/null -v
MAYGEN is generating isomers of C5N2O5H1...
The number of structures is: 0
Time: 35.07 seconds

**Comment by MehmetAzizYirik** [comment]
@steinbeck Thanks, I updated my canBuildGraph function and it checks now the even sums.
