### ISSUE TITLE
MAYGEN.jar fails to run due to class not found

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/MAYGEN#2]
I can clone the repo and build the jar with mvn package, but when I then do

java -jar target/MAYGEN-jar-with-dependencies.jar 
I get
Error: Could not find or load main class MAYGEN.MAYGEN

Suggestion: clone the repo to an empty location and reproduce the problem.

**Comment by steinbeck** [comment]
I managed to clean up my version so that it finds the class. 
I can push the changes once we have confirmed that things would be working also for you guys.
I would also strongly suggest to change the package of MAYGEN to just MAYGEN and not MAYGEN.MAYGEN, which makes not much sense.

**Comment by javadev** [comment]
@steinbeck I prepared a fix for this issue. https://github.com/MehmetAzizYirik/MAYGEN/pull/3

**Comment by steinbeck** [comment]
Thanks, Valentyn. I cloned a fresh copy of the repo and ran mvn package. 1. I am not sure that package should run all the tests. That makes compiling and packaging very slow. 
When I run
mvn package 
java -jar target/MAYGEN-jar-with-dependencies.jar 
Error: Could not find or load main class MAYGEN.MAYGEN

My suggestion: 

1. Change the package of all classes to just MAYGEN and not MAYGEN.MAYGEN
2. Move all .java files into the base directory (such as src/main/java/). No need for subdirectories. 

Those changes and some simplification of the pom.xml made things work for me in another copy.

**Comment by javadev** [comment]
Do you clone forked repository?

It looks like you check the old version.

**Comment by javadev** [comment]
The code changes not implemented yet for this repository. The repository with fix https://github.com/pytdev/MAYGEN.git
