### ISSUE TITLE
[enhancement] MAYGEN output as SMILES

### ISSUE THREAD

**Issue by adelenelai** [MehmetAzizYirik/MAYGEN#40]
Hi, any possibility to get SMILES as alternative output to SDF? This way we would get more compact output files and would be easier to plot the molecules using standard toolkits. Thanks!

**Comment by javadev** [comment]
@adelenelai Do you have sample files in SMILES format?

**Comment by adelenelai** [comment]
Hi @javadev , something like the attached (ignore 2nd column). Thanks!
[fluorothreanine.txt](https://github.com/MehmetAzizYirik/MAYGEN/files/6861712/fluorothreanine.txt)

**Comment by javadev** [comment]
Implemented https://github.com/MehmetAzizYirik/MAYGEN/pull/47

**Comment by javadev** [comment]
Issue may be closed, I think. The new key -smi, --smiles was added.

**Comment by MehmetAzizYirik** [comment]
We released V1.7 with -smi option.
