### ISSUE TITLE
generating output sdf

### ISSUE THREAD

**Issue by jincho1** [MehmetAzizYirik/MAYGEN#45]
Hi,

Thank you for sharing your work.  I downloaded MAYGEN-1.5.jar and did the following:

java -jar MAYGEN-1.5.jar -f C2OH4 -v -t -d /tmp/

and I got the following standard output:

MAYGEN is generating isomers of C2OH4...
The number of structures is: 3
Time: .015 seconds
C2OH4   3       .015    79

But I didn't get a sdf in /tmp folder.  I am using centos 7.9.

Thanks,

Jin

**Comment by MehmetAzizYirik** [comment]
@jincho1 Thanks for raising the issue. A small change in the version 1.5 caused the problem. Please try with V1.5 again. The jar file is updated.

**Comment by jincho1** [comment]
Thank you!  I have another question regarding the output, "C2OH4 3 .015 79".  What does the number 79 represent?  Is it the number of threads used?  Using -m argument seems to change that number, but it doesn't match the number specified.

Thanks in advance,

Jin

**Comment by MehmetAzizYirik** [comment]
Thanks for the comment Jin! I updated the readme and the jar file for the tsv explanation. Yes, the 4th column is for the number of threads. 

When I run the same formula on my windows machine and in our cluster, Linux, I got 3 for the number of threads. "C2OH4 3 .017 3". I did not get an output with 79. So I need more information for the issue you faced to be able to understand why you got such an output. Can you please open a new issue for that and give us more information about how you run the MAYGEN-1.5.jar file? Did you download the jar file or build the maven project yourself ? But in any case, the jar was built and released based on the latest src code we have in the repository.

**Comment by MehmetAzizYirik** [comment]
@jincho1 Thanks for the comment Jin! I updated the readme and the jar file for the tsv. Yes, the 4th column is for the number of threads.

When I run the same formula on my windows machine and in our cluster, Linux, I got 3 for the number of threads. "C2OH4 3 .017 3". I did not get an output with 79. So I need more information for the issue you faced to be able to understand why you got such an output. Can you please open a new issue for that and give us more information about how you run the MAYGEN-1.5.jar file? Did you download the jar file or build the maven project yourself ? But in any case, the jar was built and released based on the latest src code we have in the repository.
