### ISSUE TITLE
number of threads -> 79

### ISSUE THREAD

**Issue by jincho1** [MehmetAzizYirik/MAYGEN#48]
> When I run the same formula on my windows machine and in our cluster, Linux, I got 3 for the number of threads. "C2OH4 3 .017 3". I did not get an output with 79. So I need more information for the issue you faced to be able to understand why you got such an output. Can you please open a new issue for that and give us more information about how you run the MAYGEN-1.5.jar file? Did you download the jar file or build the maven project yourself ? But in any case, the jar was built and released based on the latest src code we have in the repository.

I downloaded MAYGEN-1.5.jar:
wget https://github.com/MehmetAzizYirik/MAYGEN/releases/download/V1.5/MAYGEN-1.5.jar

and ran like this:

java -jar MAYGEN-1.5.jar -f C2OH4 -v -t
MAYGEN is generating isomers of C2OH4...
The number of structures is: 3
Time: .015 seconds
C2OH4   3       .015    79

I ran the program in  Linux release 7.9.2009

I also noticed that there is a problem with the sdf the program generates when I used a more complex formula

java -jar MAYGEN-1.5.jar -f C10H9N3 -v -t -d temp -m 10

I copy and pasted the problem area.  It looks like each thread is writing to the file at the same time.
-----
Molecule 2
    MAYGEN 20210615
 22 22  0     0  0  0  0  0  0999 V2000

Molecule 3
    MAYGEN 20210615
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
 22 22  0     0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0

Molecule 6
    MAYGEN 20210615
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
 22 22  0     0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0

**Comment by MehmetAzizYirik** [comment]
@jincho1 Thanks a lot Jin for the explanation. We will look at why you got that 79 in your output, although we dont get such an output when we test. 

We will look at the SDF issue in the multithread mode. Please, for now, run MAYGEN in single-thread mode, so without -m option in default.

@javadev Valentyn, please take a look at the SDF issue as soon as possible.

**Comment by javadev** [comment]
We may collect the molecule block and write it once not line by line. It may help.

**Comment by javadev** [comment]
@MehmetAzizYirik I prepared a fix https://github.com/MehmetAzizYirik/MAYGEN/pull/49

**Comment by MehmetAzizYirik** [comment]
@jincho1 we already solved the issue regarding the number of threads and it is merged. Also the SDF generation issue is solved and merged to the main branch. It will be included in the future release.
