### ISSUE TITLE
SDF generation issue

### ISSUE THREAD

**Issue by Saikat248** [MehmetAzizYirik/MAYGEN#66]
Recently I have tried to generate different molecule from the chemical formula
I have compiled MAYGEN using mvn, compiled successfully. However, output sdf coordinates are all zero.
Same is true for the pre-compiled version 1.6. The command I am using under Linux is

`java -jar MAYGEN-1.7.jar -f C2OH4 -v -t -d conformer`

output sdf is shown like
`
Molecule 1
    MAYGEN 20210615
  7  6  0     0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2   0  0  0  0
  1  5  1   0  0  0  0
  2  6  1   0  0  0  0
  2  7  1   0  0  0  0
  3  1  1   0  0  0  0
  3  4  1   0  0  0  0
M  END

$$$$

Molecule 2
    MAYGEN 20210615
  7  7  0     0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1   0  0  0  0
  1  4  1   0  0  0  0
  1  5  1   0  0  0  0
  2  6  1   0  0  0  0
  2  7  1   0  0  0  0
  3  1  1   0  0  0  0
  3  2  1   0  0  0  0
M  END

$$$$

Molecule 3
    MAYGEN 20210615
  7  6  0     0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1   0  0  0  0
  1  4  1   0  0  0  0
  2  5  1   0  0  0  0
  2  6  1   0  0  0  0
  2  7  1   0  0  0  0
  3  1  2   0  0  0  0
M  END

$$$$`

Am I making any mistake?

**Comment by MehmetAzizYirik** [comment]
@Saikat248 Hi Saikat, I added today the atom coordinate generation for SDF file and in the V1.7. Since the coordinate generation slows down the algorithm, there are two options for SDF: -sdf or -sdfCoord. You can use -sdfCoord to generate also atom coordinates for your SDF.
