### ISSUE TITLE
Paralellization, -m, does not work properly in V1.7.

### ISSUE THREAD

**Issue by MehmetAzizYirik** [MehmetAzizYirik/MAYGEN#69]
While writing in SDF in parallel, it returns error. Although it generates isomers correctly, there is an issue while writing to the same SDFWriter file from different threads.

**Comment by chaileon** [comment]
Thanks! I just re-cloned your repo, and tried this:
 java -jar target/MAYGEN-1.7.jar -f c10OH16 -v -t -o odir/ -sdf -m 4
I am still getting this error:
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException

Thanks!
Hai Leong

**Comment by MehmetAzizYirik** [comment]
@chaileon We are still working on the issue in writing into SDF in multithread mode.

**Comment by javadev** [comment]
https://github.com/MehmetAzizYirik/MAYGEN/pull/77

**Comment by MehmetAzizYirik** [comment]
@chaileon We solved the issue and tested with the new release [V.1.8](https://github.com/MehmetAzizYirik/MAYGEN/releases/tag/V1.8).
