### ISSUE TITLE
Readme instructions list wrong option

### ISSUE THREAD

**Issue by jasondbiggs** [MehmetAzizYirik/MAYGEN#73]
The instructions on the readme file say

```
java -jar MAYGEN.jar -f C2OH4 -v -t -d C:\Users\UserName\Desktop\
```
but the option to specify the output directory is -o and not -d

**Comment by MehmetAzizYirik** [comment]
@jasondbiggs Thanks. It was the former name we used for the option. I changed it to "-o".
