### ISSUE TITLE
Add an option to filter invalid valences

### ISSUE THREAD

**Issue by jasondbiggs** [MehmetAzizYirik/MAYGEN#75]
When I run the input 
```
java -jar MAYGEN-1.7.jar -f C22H32O3N2 -v -t -m -smi -o /Users/jasonb/Desktop/temp
```
the first smiles that comes back is "[CH]C([C][CH2])([OH2])C1([CH])CCCC(C=CC=CC=C[OH]=CC=CC2C=C2)C[NH2]C1", which looks like

<img width="450" alt="image" src="https://user-images.githubusercontent.com/16337306/132062828-6d5c7766-b125-4e5f-9c64-7277ff44a131.png">

If the CDK is being used to generate the SMILES strings, would it be possible to filter out molecules with such nonstandard valences?  I see a pentavalent oxygen, plenty of divalent carbons, etc.  Currently I am filtering them afterwards but perhaps it could be integrated into the system.

**Comment by MehmetAzizYirik** [comment]
@jasondbiggs Although the algorithm does not generate any molecule with invalid valences, in the multithread mode while wiriting to SDF, we have this issue. We are currently working on it [SDF.](https://github.com/MehmetAzizYirik/MAYGEN/issues/69)

**Comment by steinbeck** [comment]
The bug report from jasondbiggs is about SMILES output, not SDF. The oxygen in den SMILES clearly has more than two bonds, so a reply about SDF does not address jasondbiggs bug report.

**Comment by MehmetAzizYirik** [comment]
@steinbeck right, I edited my comment.

**Comment by jasondbiggs** [comment]
If I switch to a smaller formula and turn off the `-m` option
```
java -jar MAYGEN-1.7.jar -f C10H10O2 -v -smi -o .
```
then I still end up seeing lots of tetravalent oxygen like `[CH]C1C(=C)C1(C)C2(O)O3=C=C3C2`.  Is that expected?

**Comment by MehmetAzizYirik** [comment]
@jasondbiggs No it is not. That is the other thing I am currently checking in SMILES.

**Comment by MehmetAzizYirik** [comment]
@jasondbiggs We solved the issue and tested with the new release [V.1.8](https://github.com/MehmetAzizYirik/MAYGEN/releases/tag/V1.8).
